#include "src/web/screensaver_editor.h"

String screensaverEditorHtml(bool multiScreensaver, bool hasFreeSlot) {
  String out;
  out.reserve(11800);
  out +=
    "<style>"
    ".ss-wrap{display:grid;gap:12px}"
    ".ss-card{border:1px solid var(--line-soft);border-radius:12px;padding:10px 11px;background:var(--stat-bg)}"
    ".ss-grid{display:grid;gap:10px;grid-template-columns:repeat(2,minmax(0,1fr))}"
    ".ss-grid .full{grid-column:1/-1}"
    ".ss-grid > div{min-width:0}"
    ".ss-adv{border:1px solid var(--line);border-radius:10px;padding:8px 10px;background:var(--card)}"
    ".ss-adv summary{cursor:pointer;font-weight:600;list-style:none}"
    ".ss-adv summary::-webkit-details-marker{display:none}"
    ".ss-adv summary:after{content:'▾';float:right;color:var(--muted)}"
    ".ss-adv[open] summary:after{content:'▴'}"
    ".ss-adv-body{margin-top:10px}"
    ".ss-label-row{display:flex;justify-content:space-between;align-items:center;gap:8px;margin:0 0 6px}"
    ".ss-value{font-size:12px;color:var(--muted);white-space:nowrap}"
    ".ss-value-editable{cursor:pointer;text-decoration:underline dotted;text-underline-offset:2px}"
    ".ss-value-editable:hover{color:var(--link)}"
    ".ss-value-input{width:4.8em;font-size:12px;padding:2px 5px;border:1px solid var(--line);border-radius:6px;background:var(--card);color:inherit;text-align:right}"
    ".ss-preview-wrap{display:flex;flex-direction:column;gap:8px;min-height:240px}"
    ".ss-preview-stage{flex:1;display:flex;align-items:center;justify-content:center;min-height:140px}"
    ".ss-preview-stage canvas{width:100%;max-width:520px;border:1px solid var(--line);border-radius:10px;background:#fff;image-rendering:pixelated;touch-action:none}"
    ".ss-preview-wrap #ssResetBtn{align-self:flex-start;width:auto;padding:6px 12px;font-size:13px}"
    ".ss-meta{font-size:12px;color:var(--muted)}"
    ".ss-tip{font-size:12px;color:var(--muted)}"
    ".ss-status{font-size:13px;color:var(--muted)}"
    ".ss-wrap input[type=range]{display:block;width:100%;max-width:none;box-sizing:border-box}"
    "@media(max-width:560px){.ss-grid{grid-template-columns:1fr}}"
    "</style>";

  out +=
    "<div class='card'><h2>Screensaver editor</h2>"
    "<p class='muted'>Edit on phone in browser and upload directly. Supports drag, pinch, and scroll zoom. "
    "Output is always 250&times;122, 1-bit, 3904 bytes.</p>"
    "<div class='ss-wrap'>"
    "<div class='ss-card ss-grid'>"
    "<div class='full'><div class='ss-label-row'><label for='ssEditFile'>Source image</label></div><input id='ssEditFile' type='file' accept='image/*'></div>"
    "<div class='full'><div class='ss-label-row'><label for='ssTolerance'>Black tolerance</label><span class='ss-value ss-value-editable' id='ssToleranceLabel'>0%</span></div><input id='ssTolerance' type='range' min='-100' max='100' value='0'></div>"
    "<div class='full'><label style='display:flex;gap:10px;align-items:center;font-weight:500'><input id='ssInvert' type='checkbox'><span>Invert black/white</span></label></div>"
    "<div class='full'><details class='ss-adv'><summary>Precise Control</summary><div class='ss-adv-body ss-grid'>"
    "<div><div class='ss-label-row'><label for='ssZoom'>Zoom</label><span class='ss-value ss-value-editable' id='ssZoomLabel'>100%</span></div><input id='ssZoom' type='range' min='10' max='400' value='100'></div>"
    "<div><div class='ss-label-row'><label for='ssPanX'>Move X</label><span class='ss-value ss-value-editable' id='ssPanXLabel'>0 px</span></div><input id='ssPanX' type='range' min='-250' max='250' value='0'></div>"
    "<div class='full'><div class='ss-label-row'><label for='ssPanY'>Move Y</label><span class='ss-value ss-value-editable' id='ssPanYLabel'>0 px</span></div><input id='ssPanY' type='range' min='-180' max='180' value='0'></div>"
    "</div></details></div>"
    "</div>"
    "<div class='ss-card ss-preview-wrap'>"
    "<label>Preview (drag to move, pinch or scroll to zoom)</label>"
    "<div class='ss-preview-stage'><canvas id='ssPreview' width='250' height='122'></canvas></div>"
    "<button type='button' class='btn secondary' id='ssResetBtn'>Reset fit</button>"
    "<div class='ss-meta' id='ssMeta'>No image loaded</div>"
    "</div>";

  if (multiScreensaver) {
    out +=
      "<div class='ss-card'>"
      "<div class='ss-label-row'><label for='ssDestination'>Destination</label></div>"
      "<select id='ssDestination'>"
      "<option value='slot' selected>Add to rotation slot (next free)</option>"
      "<option value='single'>Single screensaver (/sleep.bin)</option>"
      "</select></div>";
  }

  out +=
    "<div class='actions'>"
    "<button type='button' class='btn secondary' id='ssUploadBtn'>Upload edited image</button>"
    "<span class='ss-status' id='ssUploadStatus'></span>"
    "</div></div></div>";

  out += "<script>"
    "(function(){"
    "if(window.__palaSleepEditorInit)return;"
    "window.__palaSleepEditorInit=1;"
    "var W=250,H=122,ROW=32,TOTAL=H*ROW;"
    "var fileInput=document.getElementById('ssEditFile');"
    "var tol=document.getElementById('ssTolerance');"
    "var tolLbl=document.getElementById('ssToleranceLabel');"
    "var zoom=document.getElementById('ssZoom');"
    "var zoomLbl=document.getElementById('ssZoomLabel');"
    "var panX=document.getElementById('ssPanX');"
    "var panY=document.getElementById('ssPanY');"
    "var panXLbl=document.getElementById('ssPanXLabel');"
    "var panYLbl=document.getElementById('ssPanYLabel');"
    "var inv=document.getElementById('ssInvert');"
    "var canvas=document.getElementById('ssPreview');"
    "var meta=document.getElementById('ssMeta');"
    "var status=document.getElementById('ssUploadStatus');"
    "var resetBtn=document.getElementById('ssResetBtn');"
    "var uploadBtn=document.getElementById('ssUploadBtn');"
    "var dstSel=document.getElementById('ssDestination');"
    "var hasFreeSlot=";
  out += hasFreeSlot ? "true" : "false";
  out +=
    ";"
    "if(!fileInput||!tol||!zoom||!panX||!panY||!inv||!canvas||!meta||!status||!resetBtn||!uploadBtn)return;"
    "var ctx=canvas.getContext('2d',{willReadFrequently:true});"
    "var work=document.createElement('canvas');work.width=W;work.height=H;"
    "var workCtx=work.getContext('2d',{willReadFrequently:true});"
    "var sourceImage=null;"
    "var isDragging=false;"
    "var dragStartX=0,dragStartY=0,dragPanX=0,dragPanY=0;"
    "var pointers={};"
    "var pinch={active:false,startDist:0,startZoom:100,startPanX:0,startPanY:0,startMidX:0,startMidY:0};"
    "function clamp(v,min,max){return v<min?min:(v>max?max:v)}"
    "function thresholdFromTolerance(offset){"
      "var o=clamp(parseInt(offset||0,10)||0,-100,100);"
      "var delta=Math.round(o*(255-128)/100);"
      "return clamp(128+delta,0,255);"
    "}"
    "var editingLbl=null;"
    "function setLblText(lbl,text){if(lbl&&lbl!==editingLbl)lbl.textContent=text;}"
    "function setPanLabels(){setLblText(panXLbl,panX.value+' px');setLblText(panYLbl,panY.value+' px');}"
    "function setControlLabels(){"
      "var tv=parseInt(tol.value,10)||0;"
      "setLblText(tolLbl,(tv>0?'+':'')+tv+'%');"
      "setLblText(zoomLbl,zoom.value+'%');"
      "setPanLabels();"
    "}"
    "function bindValueEdit(lbl,slider){"
      "if(!lbl||!slider)return;"
      "lbl.title='Click to type a value';"
      "function finishEdit(commit){"
        "if(editingLbl!==lbl)return;"
        "var inp=lbl.querySelector('input');"
        "if(!inp)return;"
        "if(commit){"
          "var raw=String(inp.value).trim();"
          "var n=parseInt(raw,10);"
          "if(isNaN(n)&&raw.charAt(0)==='+')n=parseInt(raw.slice(1),10);"
          "if(isNaN(n))n=parseInt(slider.value,10)||0;"
          "n=clamp(n,parseInt(slider.min,10)||0,parseInt(slider.max,10)||0);"
          "slider.value=String(n);"
        "}"
        "lbl.removeChild(inp);"
        "editingLbl=null;"
        "render();"
      "}"
      "function beginEdit(){"
        "if(editingLbl||lbl.querySelector('input'))return;"
        "editingLbl=lbl;"
        "var inp=document.createElement('input');"
        "inp.type='number';"
        "inp.className='ss-value-input';"
        "inp.min=slider.min;"
        "inp.max=slider.max;"
        "inp.step='1';"
        "inp.value=String(parseInt(slider.value,10)||0);"
        "lbl.textContent='';"
        "lbl.appendChild(inp);"
        "inp.focus();"
        "if(inp.select)inp.select();"
        "inp.addEventListener('keydown',function(e){"
          "if(e.key==='Enter'){e.preventDefault();finishEdit(true);}"
          "else if(e.key==='Escape'){e.preventDefault();finishEdit(false);}"
        "});"
        "inp.addEventListener('blur',function(){finishEdit(true);});"
      "}"
      "lbl.addEventListener('click',beginEdit);"
    "}"
    "bindValueEdit(tolLbl,tol);"
    "bindValueEdit(zoomLbl,zoom);"
    "bindValueEdit(panXLbl,panX);"
    "bindValueEdit(panYLbl,panY);"
    "function fitImage(){"
      "if(!sourceImage)return;"
      "zoom.value='100';panX.value='0';panY.value='0';setControlLabels();render();"
    "}"
    "function drawSourceToWork(){"
      "workCtx.fillStyle='#fff';workCtx.fillRect(0,0,W,H);"
      "if(!sourceImage)return;"
      "var base=Math.min(W/sourceImage.width,H/sourceImage.height);"
      "var scale=base*((parseInt(zoom.value,10)||100)/100);"
      "if(!isFinite(scale)||scale<=0)scale=base;"
      "var dw=Math.max(1,Math.round(sourceImage.width*scale));"
      "var dh=Math.max(1,Math.round(sourceImage.height*scale));"
      "var x=((W-dw)/2)+(parseInt(panX.value,10)||0);"
      "var y=((H-dh)/2)+(parseInt(panY.value,10)||0);"
      "workCtx.drawImage(sourceImage,x,y,dw,dh);"
    "}"
    "function toOneBit(){"
      "var img=workCtx.getImageData(0,0,W,H);"
      "var d=img.data;"
      "var threshold=thresholdFromTolerance(tol.value);"
      "var invert=!!inv.checked;"
      "for(var i=0;i<d.length;i+=4){"
        "var lum=((d[i]*299)+(d[i+1]*587)+(d[i+2]*114))/1000;"
        "var white=(lum>=threshold);"
        "if(invert)white=!white;"
        "var c=white?255:0;"
        "d[i]=c;d[i+1]=c;d[i+2]=c;d[i+3]=255;"
      "}"
      "ctx.putImageData(img,0,0);"
      "return img;"
    "}"
    "function packBytes(img){"
      "var d=img.data;"
      "var out=new Uint8Array(TOTAL);"
      "for(var y=0;y<H;y++){"
        "for(var x=0;x<W;x++){"
          "var i=(y*W+x)*4;"
          "if(d[i]>=128){"
            "var bi=(y*ROW)+(x>>3);"
            "out[bi]=out[bi]|(1<<(x&7));"
          "}"
        "}"
      "}"
      "return out;"
    "}"
    "function render(){"
      "setControlLabels();"
      "drawSourceToWork();"
      "var oneBit=toOneBit();"
      "if(!sourceImage){meta.textContent='No image loaded';return null;}"
      "var threshold=thresholdFromTolerance(tol.value);"
      "meta.textContent='Preview: '+W+'x'+H+'  threshold '+threshold+'  bytes '+TOTAL;"
      "return oneBit;"
    "}"
    "function pointerList(){var a=[];for(var k in pointers){a.push(pointers[k]);}return a;}"
    "function dist(a,b){var dx=a.x-b.x,dy=a.y-b.y;return Math.sqrt(dx*dx+dy*dy);}"
    "function mid(a,b){return{x:(a.x+b.x)/2,y:(a.y+b.y)/2};}"
    "function beginPinchIfNeeded(){"
      "var pts=pointerList();"
      "if(pts.length===2){"
        "pinch.active=true;"
        "pinch.startDist=Math.max(8,dist(pts[0],pts[1]));"
        "pinch.startZoom=parseInt(zoom.value,10)||100;"
        "pinch.startPanX=parseInt(panX.value,10)||0;"
        "pinch.startPanY=parseInt(panY.value,10)||0;"
        "var m=mid(pts[0],pts[1]);"
        "pinch.startMidX=m.x;pinch.startMidY=m.y;"
      "} else {"
        "pinch.active=false;"
      "}"
    "}"
    "fileInput.addEventListener('change',function(){"
      "var f=fileInput.files&&fileInput.files[0];"
      "if(!f){sourceImage=null;render();return;}"
      "status.textContent='';"
      "var r=new FileReader();"
      "r.onload=function(){"
        "var im=new Image();"
        "im.onload=function(){sourceImage=im;fitImage();};"
        "im.onerror=function(){status.textContent='Could not decode image.';};"
        "im.src=r.result;"
      "};"
      "r.onerror=function(){status.textContent='Could not read image.';};"
      "r.readAsDataURL(f);"
    "});"
    "[tol,zoom,panX,panY,inv].forEach(function(el){el.addEventListener('input',render);el.addEventListener('change',render);});"
    "resetBtn.addEventListener('click',function(){fitImage();status.textContent='';});"
    "canvas.addEventListener('pointerdown',function(e){"
      "pointers[e.pointerId]={x:e.clientX,y:e.clientY};"
      "canvas.setPointerCapture(e.pointerId);"
      "var pts=pointerList();"
      "if(pts.length===1){"
        "isDragging=true;dragStartX=e.clientX;dragStartY=e.clientY;dragPanX=parseInt(panX.value,10)||0;dragPanY=parseInt(panY.value,10)||0;"
      "}"
      "beginPinchIfNeeded();"
    "});"
    "canvas.addEventListener('pointermove',function(e){"
      "if(!pointers[e.pointerId])return;"
      "pointers[e.pointerId].x=e.clientX;"
      "pointers[e.pointerId].y=e.clientY;"
      "var pts=pointerList();"
      "if(pinch.active&&pts.length===2){"
        "var d=Math.max(8,dist(pts[0],pts[1]));"
        "var ratio=d/pinch.startDist;"
        "var newZoom=Math.round(pinch.startZoom*ratio);"
        "zoom.value=String(clamp(newZoom,10,400));"
        "var m=mid(pts[0],pts[1]);"
        "panX.value=String(clamp(pinch.startPanX+Math.round(m.x-pinch.startMidX),-250,250));"
        "panY.value=String(clamp(pinch.startPanY+Math.round(m.y-pinch.startMidY),-180,180));"
        "render();"
        "return;"
      "}"
      "if(isDragging&&pts.length===1){"
        "panX.value=String(clamp(dragPanX+Math.round(e.clientX-dragStartX),-250,250));"
        "panY.value=String(clamp(dragPanY+Math.round(e.clientY-dragStartY),-180,180));"
        "render();"
      "}"
    "});"
    "function endPointer(e){"
      "delete pointers[e.pointerId];"
      "var pts=pointerList();"
      "if(pts.length===1){"
        "isDragging=true;"
        "dragStartX=pts[0].x;dragStartY=pts[0].y;"
        "dragPanX=parseInt(panX.value,10)||0;dragPanY=parseInt(panY.value,10)||0;"
      "} else {"
        "isDragging=false;"
      "}"
      "beginPinchIfNeeded();"
    "}"
    "canvas.addEventListener('pointerup',endPointer);"
    "canvas.addEventListener('pointercancel',endPointer);"
    "canvas.addEventListener('wheel',function(e){"
      "if(!sourceImage)return;"
      "e.preventDefault();"
      "var z=parseInt(zoom.value,10)||100;"
      "var step=Math.max(2,Math.round(Math.abs(e.deltaY)/25));"
      "var next=z-(e.deltaY>0?step:-step);"
      "zoom.value=String(clamp(next,10,400));"
      "render();"
    "},{passive:false});"
    "uploadBtn.addEventListener('click',function(){"
      "if(!sourceImage){alert('Please choose an image first.');return;}"
      "var img=render();"
      "if(!img){status.textContent='Preview is not ready yet.';return;}"
      "var bytes=packBytes(img);"
      "var fd=new FormData();"
      "fd.append('file',new Blob([bytes],{type:'application/octet-stream'}),'sleep-editor.bin');"
      "var endpoint='/upload-sleep';"
      "if(dstSel&&dstSel.value==='slot'){"
        "if(!hasFreeSlot){status.textContent='All 8 rotation slots are full. Remove one first.';return;}"
        "endpoint='/upload-sleep-slot';"
      "}"
      "status.textContent='Uploading...';"
      "uploadBtn.disabled=true;"
      "fetch(endpoint,{method:'POST',body:fd}).then(function(res){"
        "if(!res.ok){return res.text().then(function(t){throw new Error(t||('HTTP '+res.status));});}"
        "status.textContent='Upload complete. Refreshing...';"
        "setTimeout(function(){window.location.href='/settings';},600);"
      "}).catch(function(err){"
        "var msg=err&&err.message?err.message:'error';"
        "if(msg.indexOf('Please choose an image first.')>=0){alert(msg);status.textContent='';}"
        "else{status.textContent='Upload failed: '+msg;}"
      "}).finally(function(){uploadBtn.disabled=false;});"
    "});"
    "setControlLabels();"
    "render();"
    "})();"
    "</script>";
  return out;
}
