#ifndef PALA_LANG_H
#define PALA_LANG_H

// ============================================================================
//  Language selector — included transitively via src/config.h, so every
//  translation unit sees the D_* string-literal macros without an extra
//  per-file include.
//
//  Each language header is a standalone file generated by scripts/gen_lang.py
//  from the corresponding .json source in this directory. Missing keys in
//  non-English .json files fall back to the English value at generation time.
//
//  Selection:
//    PlatformIO: -D LANG_EN / -D LANG_ES_LA in build_flags (leaf envs).
//    Arduino IDE: uncomment LANG_EN or LANG_ES_LA in Pala_One_2_1.ino.
//
//  Authoring: edit the .json files in src/lang/, then run
//    python scripts/gen_lang.py
//  PlatformIO runs the generator automatically as a pre-build hook.
//  The generated .h files are committed so Arduino IDE users (who lack
//  Python / PIO) always have valid headers.
//
//  Adding a language: create <lang>.json (mirror en.json keys), add an
//  #elif arm below, add leaf envs in platformio.ini.
// ============================================================================

#if !defined(LANG_EN) && !defined(LANG_ES_LA)
  #pragma message ("No LANG_* selected; defaulting to LANG_EN.")
  #define LANG_EN
#endif

#if defined(LANG_ES_LA)
  #include "src/lang/es_la.h"
#elif defined(LANG_EN)
  #include "src/lang/en.h"
#endif

#endif  // PALA_LANG_H
